const CACHE_NAME = 'chess-coach-v1.4.7';
const ASSETS = [
  './',
  './app.php',
  './games.php',
  './import-chesscom.php',
  './analysis-pending.php',
  './review.php',
  './profile.php',
  './training.php',
  './training-exercise.php',
  './openings-lab.php',
  './player-dna.php',
  './assets/css/app.css',
  './assets/js/app.js',
  './assets/js/dashboard.js',
  './assets/js/games.js',
  './assets/js/training.js',
  './assets/js/openings_lab.js',
  './assets/js/player_dna.js',
  './assets/js/layout.js',
  './assets/js/chesscom.js',
  './assets/js/analysis_queue.js',
  './assets/js/review.js',
  './assets/images/analysis_background.jpg',
  './assets/images/background_login.png',
  './assets/images/games_background.jpg',
  './assets/images/home_greeting_background.jpg',
  './assets/images/import_background.jpg',
  './assets/images/lab_background.jpg',
  './assets/images/review_background.jpg',
  './assets/images/statistics_background.jpg',
  './assets/images/training_background.jpg',
  './assets/images/focus/ojo.png',
  './assets/images/focus/diana.png',
  './assets/images/focus/bandera.png',
  './assets/pieces/Set%201/bb.png',
  './assets/pieces/Set%201/bk.png',
  './assets/pieces/Set%201/bn.png',
  './assets/pieces/Set%201/bp.png',
  './assets/pieces/Set%201/bq.png',
  './assets/pieces/Set%201/br.png',
  './assets/pieces/Set%201/wb.png',
  './assets/pieces/Set%201/wk.png',
  './assets/pieces/Set%201/wn.png',
  './assets/pieces/Set%201/wp.png',
  './assets/pieces/Set%201/wq.png',
  './assets/pieces/Set%201/wr.png',
  './assets/pieces/Set%202/bb.png',
  './assets/pieces/Set%202/bk.png',
  './assets/pieces/Set%202/bn.png',
  './assets/pieces/Set%202/bp.png',
  './assets/pieces/Set%202/bq.png',
  './assets/pieces/Set%202/br.png',
  './assets/pieces/Set%202/wb.png',
  './assets/pieces/Set%202/wk.png',
  './assets/pieces/Set%202/wn.png',
  './assets/pieces/Set%202/wp.png',
  './assets/pieces/Set%202/wq.png',
  './assets/pieces/Set%202/wr.png',
  './assets/pieces/Set%203/bb.png',
  './assets/pieces/Set%203/bk.png',
  './assets/pieces/Set%203/bn.png',
  './assets/pieces/Set%203/bp.png',
  './assets/pieces/Set%203/bq.png',
  './assets/pieces/Set%203/br.png',
  './assets/pieces/Set%203/wb.png',
  './assets/pieces/Set%203/wk.png',
  './assets/pieces/Set%203/wn.png',
  './assets/pieces/Set%203/wp.png',
  './assets/pieces/Set%203/wq.png',
  './assets/pieces/Set%203/wr.png',
  './assets/icons/favicon.ico',
  './assets/icons/icon-192.png',
  './assets/icons/icon-512.png',
  './assets/icons/logo-approved.png',
  './manifest.webmanifest'
];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS).catch(() => null)));
  self.skipWaiting();
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))));
  self.clients.claim();
});
self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  event.respondWith(fetch(req).catch(() => caches.match(req)));
});
