-- Chess Coach v1.4.3
-- Autonomous ECO reference catalog (A00-E99).
-- Canonical Spanish labels derived from lichess-org/chess-openings commit 292fd0468068f58bb244f7fe1c3e573e493c3c53.
-- Source data is CC0-1.0. ECO codes are broad categories; these labels do not claim exact line detection.

CREATE TABLE IF NOT EXISTS opening_families (
  family_key VARCHAR(80) NOT NULL,
  family_name VARCHAR(160) NOT NULL,
  sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (family_key),
  UNIQUE KEY uq_opening_families_name (family_name),
  KEY idx_opening_families_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS eco_codes (
  eco_code CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  family_key VARCHAR(80) NOT NULL,
  opening_name VARCHAR(160) NOT NULL,
  variation_name VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (eco_code),
  KEY idx_eco_codes_family (family_key),
  CONSTRAINT fk_eco_codes_family FOREIGN KEY (family_key) REFERENCES opening_families(family_key)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO opening_families (family_key, family_name, sort_order) VALUES
('irregular_openings', 'Aperturas irregulares', 1),
('nimzo_larsen_attack', 'Ataque Nimzo-Larsen', 2),
('bird_opening', 'Apertura Bird', 3),
('zukertort_opening', 'Apertura Zukertort', 5),
('kings_indian_attack', 'Ataque Indio de Rey', 8),
('reti_opening', 'Apertura Réti', 10),
('english_opening', 'Apertura Inglesa', 11),
('queens_pawn_game', 'Aperturas de Peón de Dama', 41),
('modern_defense', 'Defensa Moderna', 43),
('benoni_defense', 'Defensa Benoni', 44),
('indian_defense', 'Defensa India', 46),
('pseudo_queens_indian_defense', 'Pseudo-Defensa India de Dama', 48),
('east_indian_defense', 'Defensa India Oriental', 49),
('old_indian_defense', 'Defensa India Antigua', 54),
('benko_gambit', 'Gambito Benko', 58),
('dutch_defense', 'Defensa Holandesa', 81),
('kings_pawn_game', 'Aperturas de Peón de Rey', 101),
('scandinavian_defense', 'Defensa Escandinava', 102),
('alekhine_defense', 'Defensa Alekhine', 103),
('pirc_defense', 'Defensa Pirc', 109),
('caro_kann_defense', 'Defensa Caro-Kann', 111),
('sicilian_defense', 'Defensa Siciliana', 121),
('french_defense', 'Defensa Francesa', 201),
('center_game', 'Apertura Central', 222),
('bishops_opening', 'Apertura del Alfil', 224),
('vienna_game', 'Apertura Vienesa', 226),
('kings_gambit', 'Gambito de Rey', 231),
('kings_knight_opening', 'Apertura del Caballo de Rey', 241),
('philidor_defense', 'Defensa Philidor', 242),
('petrov_defense', 'Defensa Petrov', 243),
('scotch_game', 'Apertura Escocesa', 246),
('three_knights_opening', 'Apertura de los Tres Caballos', 247),
('four_knights_game', 'Apertura de los Cuatro Caballos', 248),
('italian_game', 'Apertura Italiana', 251),
('ruy_lopez', 'Apertura Española', 261),
('rapport_jobava_system', 'Sistema Rapport-Jobava', 302),
('queens_gambit', 'Gambito de Dama', 307),
('slav_defense', 'Defensa Eslava', 311),
('tarrasch_defense', 'Defensa Tarrasch', 333),
('semi_slav_defense', 'Defensa Semi-Eslava', 344),
('neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 371),
('grunfeld_defense', 'Defensa Grünfeld', 381),
('catalan_opening', 'Apertura Catalana', 401),
('bogo_indian_defense', 'Defensa Bogoindia', 412),
('queens_indian_defense', 'Defensa India de Dama', 413),
('nimzo_indian_defense', 'Defensa Nimzoindia', 421),
('kings_indian_defense', 'Defensa India de Rey', 461)
ON DUPLICATE KEY UPDATE
  family_name = VALUES(family_name),
  sort_order = VALUES(sort_order);

INSERT INTO eco_codes (eco_code, family_key, opening_name, variation_name) VALUES
('A00', 'irregular_openings', 'Aperturas irregulares', NULL),
('A01', 'nimzo_larsen_attack', 'Ataque Nimzo-Larsen', NULL),
('A02', 'bird_opening', 'Apertura Bird', NULL),
('A03', 'bird_opening', 'Apertura Bird', 'Variante Holandesa'),
('A04', 'zukertort_opening', 'Apertura Zukertort', NULL),
('A05', 'zukertort_opening', 'Apertura Zukertort', NULL),
('A06', 'zukertort_opening', 'Apertura Zukertort', NULL),
('A07', 'kings_indian_attack', 'Ataque Indio de Rey', NULL),
('A08', 'kings_indian_attack', 'Ataque Indio de Rey', 'Variante Siciliana'),
('A09', 'reti_opening', 'Apertura Réti', NULL),
('A10', 'english_opening', 'Apertura Inglesa', NULL),
('A11', 'english_opening', 'Apertura Inglesa', 'Sistema defensivo Caro-Kann'),
('A12', 'reti_opening', 'Apertura Réti', 'Variante Angloeslava, Variante Bogoljubow'),
('A13', 'english_opening', 'Apertura Inglesa', 'Defensa Agincourt'),
('A14', 'english_opening', 'Apertura Inglesa', 'Defensa Agincourt, Neocatalana rehusada'),
('A15', 'english_opening', 'Apertura Inglesa', 'Defensa Angloindia'),
('A16', 'english_opening', 'Apertura Inglesa', 'Defensa Angloindia, Variante del Caballo de Dama'),
('A17', 'english_opening', 'Apertura Inglesa', 'Defensa Angloindia, Sistema Erizo'),
('A18', 'english_opening', 'Apertura Inglesa', 'Variante Mikenas-Carls'),
('A19', 'english_opening', 'Apertura Inglesa', 'Mikenas-Carls, Siciliana'),
('A20', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey'),
('A21', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Siciliana invertida'),
('A22', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Variante de los Dos Caballos'),
('A23', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Variante de los Dos Caballos, Variante Keres'),
('A24', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Variante de los Dos Caballos, Línea Fianchetto'),
('A25', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Siciliana cerrada invertida'),
('A26', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Sistema cerrado, Simetría completa'),
('A27', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Sistema de los Tres Caballos'),
('A28', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Variante de los Cuatro Caballos'),
('A29', 'english_opening', 'Apertura Inglesa', 'Variante Inglesa de Rey, Variante de los Cuatro Caballos, Línea Fianchetto'),
('A30', 'english_opening', 'Apertura Inglesa', 'Variante simétrica'),
('A31', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Variante Anti-Benoni'),
('A32', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Variante Anti-Benoni, Defensa Spielmann'),
('A33', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Variante Anti-Benoni, Defensa Spielmann'),
('A34', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Variante normal'),
('A35', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Variante de los Dos Caballos'),
('A36', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Dos Caballos, Variante del fianchetto'),
('A37', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Tres Caballos, Variante del fianchetto'),
('A38', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Línea Simetría completa'),
('A39', 'english_opening', 'Apertura Inglesa', 'Variante simétrica, Variante Mecking'),
('A40', 'queens_pawn_game', 'Apertura del Peón de Dama', NULL),
('A41', 'queens_pawn_game', 'Apertura del Peón de Dama', NULL),
('A42', 'modern_defense', 'Defensa Moderna', 'Sistema Averbakh'),
('A43', 'benoni_defense', 'Defensa Benoni', 'Benoni antigua'),
('A44', 'benoni_defense', 'Defensa Benoni', 'Benoni antigua'),
('A45', 'indian_defense', 'Defensa India', NULL),
('A46', 'indian_defense', 'Defensa India', 'Variante de los Caballos'),
('A47', 'pseudo_queens_indian_defense', 'Pseudo-Defensa India de Dama', NULL),
('A48', 'east_indian_defense', 'Defensa India Oriental', NULL),
('A49', 'indian_defense', 'Defensa India', 'Variante Przepiorka'),
('A50', 'indian_defense', 'Defensa India', 'Variante normal'),
('A51', 'indian_defense', 'Defensa India', 'Gambito Budapest'),
('A52', 'indian_defense', 'Defensa India', 'Gambito Budapest aceptado, Línea principal'),
('A53', 'old_indian_defense', 'Defensa India Antigua', NULL),
('A54', 'old_indian_defense', 'Defensa India Antigua', 'India Tartakower'),
('A55', 'old_indian_defense', 'Defensa India Antigua', 'Variante normal'),
('A56', 'benoni_defense', 'Defensa Benoni', NULL),
('A57', 'benko_gambit', 'Gambito Benko', NULL),
('A58', 'benko_gambit', 'Gambito Benko aceptado', 'Variante completamente aceptada'),
('A59', 'benko_gambit', 'Gambito Benko aceptado', 'Yugoslava'),
('A60', 'benoni_defense', 'Defensa Benoni', 'Variante moderna'),
('A61', 'benoni_defense', 'Defensa Benoni', NULL),
('A62', 'benoni_defense', 'Defensa Benoni', 'Variante del fianchetto'),
('A63', 'benoni_defense', 'Defensa Benoni', 'Variante del fianchetto, Defensa Hastings'),
('A64', 'benoni_defense', 'Defensa Benoni', 'Variante del fianchetto, Defensa Hastings, Línea principal'),
('A65', 'benoni_defense', 'Defensa Benoni', 'Línea del Peón de Rey'),
('A66', 'benoni_defense', 'Defensa Benoni', 'Variante de la tormenta de peones'),
('A67', 'benoni_defense', 'Defensa Benoni', 'Variante Taimanov'),
('A68', 'benoni_defense', 'Defensa Benoni', 'Ataque de los Cuatro Peones'),
('A69', 'benoni_defense', 'Defensa Benoni', 'Ataque de los Cuatro Peones, Línea principal'),
('A70', 'benoni_defense', 'Defensa Benoni', 'Variante clásica'),
('A71', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Ataque Averbakh-Grivas'),
('A72', 'benoni_defense', 'Defensa Benoni', 'Variante clásica'),
('A73', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Línea principal'),
('A74', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Línea completa'),
('A75', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Contraataque argentino'),
('A76', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Defensa Czerniak'),
('A77', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Defensa Czerniak, Línea Tal'),
('A78', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Defensa Czerniak'),
('A79', 'benoni_defense', 'Defensa Benoni', 'Variante clásica, Defensa Czerniak'),
('A80', 'dutch_defense', 'Defensa Holandesa', NULL),
('A81', 'dutch_defense', 'Defensa Holandesa', 'Ataque de fianchetto'),
('A82', 'dutch_defense', 'Defensa Holandesa', 'Gambito Staunton'),
('A83', 'dutch_defense', 'Defensa Holandesa', 'Gambito Staunton'),
('A84', 'dutch_defense', 'Defensa Holandesa', NULL),
('A85', 'dutch_defense', 'Defensa Holandesa', 'Variante del Caballo de Dama'),
('A86', 'dutch_defense', 'Defensa Holandesa', 'Variante del fianchetto'),
('A87', 'dutch_defense', 'Defensa Holandesa', 'Variante Leningrado'),
('A88', 'dutch_defense', 'Defensa Holandesa', 'Variante Leningrado, Variante Varsovia'),
('A89', 'dutch_defense', 'Defensa Holandesa', 'Variante Leningrado, Variante Matulovic'),
('A90', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica'),
('A91', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica'),
('A92', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica'),
('A93', 'dutch_defense', 'Defensa Holandesa', 'Variante Muro de Piedra, Variante Botvinnik'),
('A94', 'dutch_defense', 'Defensa Holandesa', 'Variante Muro de Piedra'),
('A95', 'dutch_defense', 'Defensa Holandesa', 'Variante Muro de Piedra'),
('A96', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica'),
('A97', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica, Variante Ilyin-Zhenevsky'),
('A98', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica, Variante Ilyin-Zhenevsky, Línea Alatortsev-Lisitsyn'),
('A99', 'dutch_defense', 'Defensa Holandesa', 'Variante clásica, Variante Ilyin-Zhenevsky, Línea principal moderna'),
('B00', 'kings_pawn_game', 'Aperturas irregulares de Peón de Rey', NULL),
('B01', 'scandinavian_defense', 'Defensa Escandinava', NULL),
('B02', 'alekhine_defense', 'Defensa Alekhine', NULL),
('B03', 'alekhine_defense', 'Defensa Alekhine', NULL),
('B04', 'alekhine_defense', 'Defensa Alekhine', 'Variante moderna'),
('B05', 'alekhine_defense', 'Defensa Alekhine', 'Variante moderna, Línea principal'),
('B06', 'modern_defense', 'Defensa Moderna', NULL),
('B07', 'kings_pawn_game', 'Apertura del Peón de Rey', 'Defensa Maróczy'),
('B08', 'pirc_defense', 'Defensa Pirc', 'Variante clásica'),
('B09', 'pirc_defense', 'Defensa Pirc', 'Ataque Austriaco'),
('B10', 'caro_kann_defense', 'Defensa Caro-Kann', NULL),
('B11', 'caro_kann_defense', 'Defensa Caro-Kann', 'Ataque de los Dos Caballos, Variante Mindeno'),
('B12', 'caro_kann_defense', 'Defensa Caro-Kann', NULL),
('B13', 'caro_kann_defense', 'Defensa Caro-Kann', 'Variante del cambio'),
('B14', 'caro_kann_defense', 'Defensa Caro-Kann', 'Ataque Panov'),
('B15', 'caro_kann_defense', 'Defensa Caro-Kann', NULL),
('B16', 'caro_kann_defense', 'Defensa Caro-Kann', 'Variante Finlandesa'),
('B17', 'caro_kann_defense', 'Defensa Caro-Kann', 'Variante Karpov'),
('B18', 'caro_kann_defense', 'Defensa Caro-Kann', 'Variante clásica'),
('B19', 'caro_kann_defense', 'Defensa Caro-Kann', 'Variante clásica'),
('B20', 'sicilian_defense', 'Defensa Siciliana', NULL),
('B21', 'sicilian_defense', 'Defensa Siciliana', 'Ataque McDonnell'),
('B22', 'sicilian_defense', 'Defensa Siciliana', 'Variante Alapin'),
('B23', 'sicilian_defense', 'Defensa Siciliana', 'Variante cerrada'),
('B24', 'sicilian_defense', 'Defensa Siciliana', 'Variante cerrada, Variante del fianchetto'),
('B25', 'sicilian_defense', 'Defensa Siciliana', 'Variante cerrada'),
('B26', 'sicilian_defense', 'Defensa Siciliana', 'Variante cerrada'),
('B27', 'sicilian_defense', 'Defensa Siciliana', NULL),
('B28', 'sicilian_defense', 'Defensa Siciliana', 'Variante O''Kelly'),
('B29', 'sicilian_defense', 'Defensa Siciliana', 'Variante Nimzowitsch'),
('B30', 'sicilian_defense', 'Defensa Siciliana', 'Siciliana antigua'),
('B31', 'sicilian_defense', 'Defensa Siciliana', 'Ataque Nyezhmetdinov-Rossolimo, Variante del fianchetto'),
('B32', 'sicilian_defense', 'Defensa Siciliana', 'Variante abierta'),
('B33', 'sicilian_defense', 'Defensa Siciliana', 'Variante abierta'),
('B34', 'sicilian_defense', 'Defensa Siciliana', 'Dragón acelerado, Variante moderna'),
('B35', 'sicilian_defense', 'Defensa Siciliana', 'Dragón acelerado, Variante Moderna Bc4'),
('B36', 'sicilian_defense', 'Defensa Siciliana', 'Dragón acelerado, Estructura Maróczy'),
('B37', 'sicilian_defense', 'Defensa Siciliana', 'Dragón acelerado, Estructura Maróczy'),
('B38', 'sicilian_defense', 'Defensa Siciliana', 'Dragón acelerado, Estructura Maróczy'),
('B39', 'sicilian_defense', 'Defensa Siciliana', 'Dragón acelerado, Estructura Maróczy, Variante Breyer'),
('B40', 'sicilian_defense', 'Defensa Siciliana', 'Variante Francesa'),
('B41', 'sicilian_defense', 'Defensa Siciliana', 'Variante Kan'),
('B42', 'sicilian_defense', 'Defensa Siciliana', 'Variante Kan, Variante moderna'),
('B43', 'sicilian_defense', 'Defensa Siciliana', 'Variante Kan, Variante del Caballo'),
('B44', 'sicilian_defense', 'Defensa Siciliana', 'Variante Taimanov'),
('B45', 'sicilian_defense', 'Defensa Siciliana', 'Variante Taimanov'),
('B46', 'sicilian_defense', 'Defensa Siciliana', 'Variante Taimanov'),
('B47', 'sicilian_defense', 'Defensa Siciliana', 'Variante Taimanov, Variante Bastrikov'),
('B48', 'sicilian_defense', 'Defensa Siciliana', 'Variante Taimanov, Variante Bastrikov, Ataque Inglés'),
('B49', 'sicilian_defense', 'Defensa Siciliana', 'Variante Taimanov, Variante Bastrikov'),
('B50', 'sicilian_defense', 'Defensa Siciliana', 'Variantes modernas'),
('B51', 'sicilian_defense', 'Defensa Siciliana', 'Variante Moscú'),
('B52', 'sicilian_defense', 'Defensa Siciliana', 'Variante Moscú, Línea principal'),
('B53', 'sicilian_defense', 'Defensa Siciliana', 'Variante Chekhover'),
('B54', 'sicilian_defense', 'Defensa Siciliana', 'Variantes modernas, Línea principal'),
('B55', 'sicilian_defense', 'Defensa Siciliana', 'Variante Prins, Ataque de Venecia'),
('B56', 'sicilian_defense', 'Defensa Siciliana', 'Variante clásica'),
('B57', 'sicilian_defense', 'Defensa Siciliana', 'Variante clásica, Ataque Sozin'),
('B58', 'sicilian_defense', 'Defensa Siciliana', 'Variante clásica'),
('B59', 'sicilian_defense', 'Defensa Siciliana', 'Variante Boleslavsky'),
('B60', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer'),
('B61', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante moderna'),
('B62', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer'),
('B63', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante tradicional'),
('B64', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante clásica'),
('B65', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Ataque Rauzer'),
('B66', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante Neomoderna, Desviaciones tempranas'),
('B67', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante Neomoderna'),
('B68', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante Neomoderna'),
('B69', 'sicilian_defense', 'Defensa Siciliana', 'Variante Richter-Rauzer, Variante Neomoderna, Ataque Nyezhmetdinov'),
('B70', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón'),
('B71', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Variante Levenfish'),
('B72', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón'),
('B73', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Variante clásica'),
('B74', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Variante clásica, Línea normal'),
('B75', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Ataque Yugoslavo, Desviaciones tempranas'),
('B76', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Ataque Yugoslavo'),
('B77', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Ataque Yugoslavo, Línea principal'),
('B78', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Ataque Yugoslavo'),
('B79', 'sicilian_defense', 'Defensa Siciliana', 'Variante del Dragón, Ataque Yugoslavo'),
('B80', 'sicilian_defense', 'Defensa Siciliana', 'Variante Scheveningen'),
('B81', 'sicilian_defense', 'Defensa Siciliana', 'Variante Scheveningen, Ataque Keres'),
('B82', 'sicilian_defense', 'Defensa Siciliana', 'Variante Scheveningen, Ataque Matanovic'),
('B83', 'sicilian_defense', 'Defensa Siciliana', 'Variante Scheveningen, Variante clásica'),
('B84', 'sicilian_defense', 'Defensa Siciliana', 'Variante Scheveningen, Variante clásica'),
('B85', 'sicilian_defense', 'Defensa Siciliana', 'Variante Scheveningen, Variante clásica, Variante Paulsen'),
('B86', 'sicilian_defense', 'Defensa Siciliana', 'Ataque Sozin'),
('B87', 'sicilian_defense', 'Defensa Siciliana', 'Ataque Sozin, Variante de flanco'),
('B88', 'sicilian_defense', 'Defensa Siciliana', 'Ataque Sozin, Variante Leonhardt'),
('B89', 'sicilian_defense', 'Defensa Siciliana', 'Ataque Sozin, Línea principal'),
('B90', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf'),
('B91', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf, Variante Zagreb'),
('B92', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf, Variante Opocensky'),
('B93', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf, Variante Amsterdam'),
('B94', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf'),
('B95', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf'),
('B96', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf'),
('B97', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf, Variante del Peón Envenenado'),
('B98', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf'),
('B99', 'sicilian_defense', 'Defensa Siciliana', 'Variante Najdorf, Línea principal'),
('C00', 'french_defense', 'Defensa Francesa', NULL),
('C01', 'french_defense', 'Defensa Francesa', 'Variante del cambio'),
('C02', 'french_defense', 'Defensa Francesa', 'Variante del Avance'),
('C03', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch'),
('C04', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch, Defensa Guimard, Línea principal'),
('C05', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch, Variante Cerrada'),
('C06', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch, Variante Cerrada, Línea principal'),
('C07', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch, Sistema Abierta'),
('C08', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch, Sistema Abierta'),
('C09', 'french_defense', 'Defensa Francesa', 'Variante Tarrasch, Sistema Abierta, Línea principal'),
('C10', 'french_defense', 'Defensa Francesa', 'Variante Paulsen'),
('C11', 'french_defense', 'Defensa Francesa', 'Variante clásica'),
('C12', 'french_defense', 'Defensa Francesa', 'Variante McCutcheon'),
('C13', 'french_defense', 'Defensa Francesa', 'Variante clásica, Variante normal'),
('C14', 'french_defense', 'Defensa Francesa', 'Variante clásica'),
('C15', 'french_defense', 'Defensa Francesa', 'Variante Winawer'),
('C16', 'french_defense', 'Defensa Francesa', 'Variante Winawer, Variante del Avance'),
('C17', 'french_defense', 'Defensa Francesa', 'Variante Winawer, Variante del Avance'),
('C18', 'french_defense', 'Defensa Francesa', 'Variante Winawer, Variante del Avance'),
('C19', 'french_defense', 'Defensa Francesa', 'Variante Winawer, Variante posicional'),
('C20', 'kings_pawn_game', 'Apertura del Peón de Rey', NULL),
('C21', 'center_game', 'Apertura Central aceptada', NULL),
('C22', 'center_game', 'Apertura Central', 'Variante normal'),
('C23', 'bishops_opening', 'Apertura del Alfil', NULL),
('C24', 'bishops_opening', 'Apertura del Alfil', 'Defensa Berlinesa'),
('C25', 'vienna_game', 'Apertura Vienesa', NULL),
('C26', 'vienna_game', 'Apertura Vienesa', 'Variante Falkbeer'),
('C27', 'vienna_game', 'Apertura Vienesa', 'Variante Frankenstein-Dracula'),
('C28', 'vienna_game', 'Apertura Vienesa', 'Variante Stanley, Variante de los Tres Caballos'),
('C29', 'vienna_game', 'Apertura Vienesa', 'Gambito de Viena'),
('C30', 'kings_gambit', 'Gambito de Rey', NULL),
('C31', 'kings_gambit', 'Gambito de Rey rehusado', 'Falkbeer Contragambito'),
('C32', 'kings_gambit', 'Gambito de Rey rehusado', 'Falkbeer Contragambito, Charousek Gambito Aceptado'),
('C33', 'kings_gambit', 'Gambito de Rey aceptado', NULL),
('C34', 'kings_gambit', 'Gambito de Rey aceptado', 'Gambito del Caballo de Rey'),
('C35', 'kings_gambit', 'Gambito de Rey aceptado', 'Defensa Cunningham'),
('C36', 'kings_gambit', 'Gambito de Rey aceptado', 'Defensa Moderna'),
('C37', 'kings_gambit', 'Gambito de Rey aceptado', 'Gambito Quaade'),
('C38', 'kings_gambit', 'Gambito de Rey aceptado', 'Variante tradicional'),
('C39', 'kings_gambit', 'Gambito de Rey aceptado', 'Gambito del Caballo de Rey'),
('C40', 'kings_knight_opening', 'Apertura del Caballo de Rey', NULL),
('C41', 'philidor_defense', 'Defensa Philidor', NULL),
('C42', 'petrov_defense', 'Defensa Petrov', NULL),
('C43', 'petrov_defense', 'Defensa Petrov', 'Ataque Moderna'),
('C44', 'kings_knight_opening', 'Apertura del Caballo de Rey', 'Variante normal'),
('C45', 'scotch_game', 'Apertura Escocesa', NULL),
('C46', 'three_knights_opening', 'Apertura de los Tres Caballos', NULL),
('C47', 'four_knights_game', 'Apertura de los Cuatro Caballos', NULL),
('C48', 'four_knights_game', 'Apertura de los Cuatro Caballos', 'Variante Española'),
('C49', 'four_knights_game', 'Apertura de los Cuatro Caballos', 'Variante Española, Doble Española'),
('C50', 'italian_game', 'Apertura Italiana', NULL),
('C51', 'italian_game', 'Apertura Italiana', 'Gambito Evans'),
('C52', 'italian_game', 'Apertura Italiana', 'Gambito Evans, Línea principal'),
('C53', 'italian_game', 'Apertura Italiana', 'Variante clásica'),
('C54', 'italian_game', 'Apertura Italiana', 'Variante clásica'),
('C55', 'italian_game', 'Apertura Italiana', 'Defensa de los Dos Caballos'),
('C56', 'italian_game', 'Apertura Italiana', 'Defensa de los Dos Caballos, Variante Abierta'),
('C57', 'italian_game', 'Apertura Italiana', 'Defensa de los Dos Caballos, Ataque del Caballo'),
('C58', 'italian_game', 'Apertura Italiana', 'Defensa de los Dos Caballos, Defensa Polerio'),
('C59', 'italian_game', 'Apertura Italiana', 'Defensa de los Dos Caballos, Defensa Polerio, Defensa Suhle'),
('C60', 'ruy_lopez', 'Apertura Española', NULL),
('C61', 'ruy_lopez', 'Apertura Española', 'Variante Bird'),
('C62', 'ruy_lopez', 'Apertura Española', 'Defensa Steinitz'),
('C63', 'ruy_lopez', 'Apertura Española', 'Defensa Schliemann'),
('C64', 'ruy_lopez', 'Apertura Española', 'Variante clásica'),
('C65', 'ruy_lopez', 'Apertura Española', 'Defensa Berlinesa'),
('C66', 'ruy_lopez', 'Apertura Española', 'Defensa Berlinesa, Defensa Steinitz mejorada'),
('C67', 'ruy_lopez', 'Apertura Española', 'Defensa Berlinesa, Gambito Río aceptado'),
('C68', 'ruy_lopez', 'Apertura Española', 'Variante del cambio'),
('C69', 'ruy_lopez', 'Apertura Española', 'Variante del cambio, Variante normal'),
('C70', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy'),
('C71', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Defensa Moderna Steinitz'),
('C72', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Defensa Moderna Steinitz'),
('C73', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Defensa Moderna Steinitz'),
('C74', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Defensa Moderna Steinitz'),
('C75', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Defensa Moderna Steinitz'),
('C76', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Defensa Moderna Steinitz, Variante del fianchetto'),
('C77', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Gambito Jaffe'),
('C78', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy'),
('C79', 'ruy_lopez', 'Apertura Española', 'Defensa Morphy, Steinitz diferida'),
('C80', 'ruy_lopez', 'Apertura Española', 'Variante abierta'),
('C81', 'ruy_lopez', 'Apertura Española', 'Variante abierta, Ataque Howell'),
('C82', 'ruy_lopez', 'Apertura Española', 'Variante abierta'),
('C83', 'ruy_lopez', 'Apertura Española', 'Variante abierta, Defensa Clásica'),
('C84', 'ruy_lopez', 'Apertura Española', 'Variante cerrada'),
('C85', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Diferida Cambio'),
('C86', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Ataque Worrall'),
('C87', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Variante Averbakh'),
('C88', 'ruy_lopez', 'Apertura Española', 'Variante cerrada'),
('C89', 'ruy_lopez', 'Apertura Española', 'Ataque Marshall'),
('C90', 'ruy_lopez', 'Apertura Española', 'Variante cerrada'),
('C91', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Variante Yates'),
('C92', 'ruy_lopez', 'Apertura Española', 'Variante cerrada'),
('C93', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Defensa Smyslov'),
('C94', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Defensa Breyer'),
('C95', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Breyer'),
('C96', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Defensa Chigorin'),
('C97', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Defensa Chigorin'),
('C98', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Defensa Chigorin'),
('C99', 'ruy_lopez', 'Apertura Española', 'Variante cerrada, Defensa Chigorin, Sistema Panov'),
('D00', 'queens_pawn_game', 'Apertura del Peón de Dama', NULL),
('D01', 'rapport_jobava_system', 'Sistema Rapport-Jobava', NULL),
('D02', 'queens_pawn_game', 'Apertura del Peón de Dama', 'Variante Zukertort'),
('D03', 'queens_pawn_game', 'Apertura del Peón de Dama', 'Ataque Torre'),
('D04', 'queens_pawn_game', 'Apertura del Peón de Dama', 'Sistema Colle'),
('D05', 'queens_pawn_game', 'Apertura del Peón de Dama', 'Sistema Colle'),
('D06', 'queens_gambit', 'Gambito de Dama', NULL),
('D07', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Chigorin'),
('D08', 'queens_gambit', 'Gambito de Dama rehusado', 'Albin Contragambito'),
('D09', 'queens_gambit', 'Gambito de Dama rehusado', 'Albin Contragambito, Variante del fianchetto'),
('D10', 'slav_defense', 'Defensa Eslava', NULL),
('D11', 'slav_defense', 'Defensa Eslava', 'Línea Moderna'),
('D12', 'slav_defense', 'Defensa Eslava', 'Variante Quiet, Defensa Schallopp'),
('D13', 'slav_defense', 'Defensa Eslava', 'Variante del cambio'),
('D14', 'slav_defense', 'Defensa Eslava', 'Variante del cambio, Línea Simétrica'),
('D15', 'slav_defense', 'Defensa Eslava', 'Variante de los Tres Caballos'),
('D16', 'slav_defense', 'Defensa Eslava', 'Variante Alapin'),
('D17', 'slav_defense', 'Defensa Eslava', 'Variante Checa'),
('D18', 'slav_defense', 'Defensa Eslava', 'Variante Checa, Sistema clásico'),
('D19', 'slav_defense', 'Defensa Eslava', 'Variante Checa, Variante Holandesa'),
('D20', 'queens_gambit', 'Gambito de Dama aceptado', NULL),
('D21', 'queens_gambit', 'Gambito de Dama aceptado', 'Variante normal'),
('D22', 'queens_gambit', 'Gambito de Dama aceptado', 'Defensa Alekhine'),
('D23', 'queens_gambit', 'Gambito de Dama aceptado', NULL),
('D24', 'queens_gambit', 'Gambito de Dama aceptado', 'Variante Showalter'),
('D25', 'queens_gambit', 'Gambito de Dama aceptado', 'Variante normal'),
('D26', 'queens_gambit', 'Gambito de Dama aceptado', 'Variante normal, Sistema Tradicional'),
('D27', 'queens_gambit', 'Gambito de Dama aceptado', 'Defensa Clásica, Línea principal'),
('D28', 'queens_gambit', 'Gambito de Dama aceptado', 'Defensa Clásica, Sistema Alekhine'),
('D29', 'queens_gambit', 'Gambito de Dama aceptado', 'Defensa Clásica, Sistema Alekhine, Línea principal'),
('D30', 'queens_gambit', 'Gambito de Dama rehusado', NULL),
('D31', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante del Caballo de Dama'),
('D32', 'tarrasch_defense', 'Defensa Tarrasch', NULL),
('D33', 'tarrasch_defense', 'Defensa Tarrasch', 'Sistema Rubinstein'),
('D34', 'tarrasch_defense', 'Defensa Tarrasch', 'Variante de Praga, Línea principal'),
('D35', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa normal'),
('D36', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante del cambio, Variante Reshevsky'),
('D37', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante de los Tres Caballos'),
('D38', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ragozin'),
('D39', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ragozin, Variante Vienesa'),
('D40', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Semi-Tarrasch'),
('D41', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Semi-Tarrasch'),
('D42', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Semi-Tarrasch, Línea principal'),
('D43', 'semi_slav_defense', 'Defensa Semi-Eslava', NULL),
('D44', 'semi_slav_defense', 'Defensa Semi-Eslava aceptada', NULL),
('D45', 'semi_slav_defense', 'Defensa Semi-Eslava', 'Línea principal'),
('D46', 'semi_slav_defense', 'Defensa Semi-Eslava', 'Línea principal'),
('D47', 'semi_slav_defense', 'Defensa Semi-Eslava', 'Variante Semi-Meran'),
('D48', 'semi_slav_defense', 'Defensa Semi-Eslava', 'Variante Meran'),
('D49', 'semi_slav_defense', 'Defensa Semi-Eslava', 'Variante Meran, Variante Blumenfeld'),
('D50', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante moderna'),
('D51', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante moderna, Defensa del Caballo'),
('D52', 'queens_gambit', 'Gambito de Dama rehusado', NULL),
('D53', 'queens_gambit', 'Gambito de Dama rehusado', NULL),
('D54', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante Neoortodoxa'),
('D55', 'queens_gambit', 'Gambito de Dama rehusado', 'Variante moderna, Línea normal'),
('D56', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Lasker'),
('D57', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Lasker, Línea principal'),
('D58', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Tartakower'),
('D59', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Tartakower, Variante Makogonov Cambio'),
('D60', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa'),
('D61', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Variante Rubinstein'),
('D62', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Variante Rubinstein, Línea Flohr'),
('D63', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Línea principal'),
('D64', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Ataque Rubinstein'),
('D65', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Ataque Rubinstein'),
('D66', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Línea Bd3'),
('D67', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Sistema Capablanca'),
('D68', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Variante clásica'),
('D69', 'queens_gambit', 'Gambito de Dama rehusado', 'Defensa Ortodoxa, Variante clásica'),
('D70', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'con g3'),
('D71', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante del cambio'),
('D72', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'con g3'),
('D73', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'con g3'),
('D74', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante Diferida Cambio'),
('D75', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante Diferida Cambio'),
('D76', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante Diferida Cambio'),
('D77', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante clásica'),
('D78', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante clásica, línea original'),
('D79', 'neo_grunfeld_defense', 'Defensa Neo-Grünfeld', 'Variante Ultradiferida Cambio'),
('D80', 'grunfeld_defense', 'Defensa Grünfeld', NULL),
('D81', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante rusa, Variante acelerada'),
('D82', 'grunfeld_defense', 'Defensa Grünfeld', 'Ataque Brinckmann'),
('D83', 'grunfeld_defense', 'Defensa Grünfeld', 'Ataque Brinckmann, Gambito Grünfeld'),
('D84', 'grunfeld_defense', 'Defensa Grünfeld', 'Ataque Brinckmann, Grünfeld Gambito Aceptado'),
('D85', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante del cambio'),
('D86', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante del cambio, Variante clásica'),
('D87', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante del cambio, Variante Spassky'),
('D88', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante del cambio, Variante Spassky'),
('D89', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante del cambio, Variante Spassky'),
('D90', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante de los Tres Caballos'),
('D91', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante de los Tres Caballos, Sistema Petrosian'),
('D92', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante de los Tres Caballos, Ataque Húngara'),
('D93', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante de los Tres Caballos, Variante Húngara'),
('D94', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante de los Tres Caballos, Variante Burille'),
('D95', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante de los Tres Caballos, Variante Vienesa'),
('D96', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante rusa'),
('D97', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante rusa'),
('D98', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante rusa, Variante Smyslov'),
('D99', 'grunfeld_defense', 'Defensa Grünfeld', 'Variante rusa, Variante Smyslov'),
('E00', 'catalan_opening', 'Apertura Catalana', NULL),
('E01', 'catalan_opening', 'Apertura Catalana', 'Defensa Abierta'),
('E02', 'catalan_opening', 'Apertura Catalana', 'Defensa Abierta'),
('E03', 'catalan_opening', 'Apertura Catalana', 'Defensa Abierta'),
('E04', 'catalan_opening', 'Apertura Catalana', 'Defensa Abierta'),
('E05', 'catalan_opening', 'Apertura Catalana', 'Defensa Abierta, Línea clásica'),
('E06', 'catalan_opening', 'Apertura Catalana', 'Variante cerrada'),
('E07', 'catalan_opening', 'Apertura Catalana', 'Variante cerrada'),
('E08', 'catalan_opening', 'Apertura Catalana', 'Variante cerrada'),
('E09', 'catalan_opening', 'Apertura Catalana', 'Variante cerrada, Línea principal'),
('E10', 'indian_defense', 'Defensa India', 'Sistema anti-Nimzoindia'),
('E11', 'bogo_indian_defense', 'Defensa Bogoindia', NULL),
('E12', 'queens_indian_defense', 'Defensa India de Dama', NULL),
('E13', 'queens_indian_defense', 'Defensa India de Dama', 'Variante Kasparov'),
('E14', 'queens_indian_defense', 'Defensa India de Dama', 'Sistema Spassky'),
('E15', 'queens_indian_defense', 'Defensa India de Dama', 'Variante del fianchetto'),
('E16', 'queens_indian_defense', 'Defensa India de Dama', 'Variante Capablanca'),
('E17', 'queens_indian_defense', 'Defensa India de Dama', 'Variante tradicional'),
('E18', 'queens_indian_defense', 'Defensa India de Dama', 'Variante clásica, Variante tradicional'),
('E19', 'queens_indian_defense', 'Defensa India de Dama', 'Variante clásica, Variante tradicional, Línea principal'),
('E20', 'nimzo_indian_defense', 'Defensa Nimzoindia', NULL),
('E21', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante de los Tres Caballos'),
('E22', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Spielmann'),
('E23', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Spielmann, Gambito Romanovsky'),
('E24', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Sämisch'),
('E25', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Sämisch'),
('E26', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Sämisch'),
('E27', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Sämisch'),
('E28', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Sämisch'),
('E29', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Sämisch'),
('E30', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Leningrado'),
('E31', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante Leningrado, Defensa Benoni'),
('E32', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica'),
('E33', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante de Zúrich'),
('E34', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante Noa'),
('E35', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante Noa'),
('E36', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante Noa'),
('E37', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante Noa'),
('E38', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante Berlinesa'),
('E39', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante clásica, Variante Berlinesa, Variante Pirc'),
('E40', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Sistema Rubinstein'),
('E41', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Sistema Rubinstein'),
('E42', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Sistema Rubinstein, Variante Rubinstein'),
('E43', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante de San Petersburgo'),
('E44', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante de San Petersburgo'),
('E45', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante de San Petersburgo, Variante Fischer'),
('E46', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal'),
('E47', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal'),
('E48', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Defensa Clásica'),
('E49', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Sistema Botvinnik'),
('E50', 'nimzo_indian_defense', 'Defensa Nimzoindia', NULL),
('E51', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Variante Ragozin'),
('E52', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Defensa Schlechter'),
('E53', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Sistema Gligoric'),
('E54', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Sistema Gligoric, Variante del cambio'),
('E55', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Sistema Gligoric, Variante Bronstein'),
('E56', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Sistema Gligoric, Defensa Bernstein'),
('E57', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Sistema Gligoric, Defensa Bernstein'),
('E58', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Defensa Bernstein, Línea del cambio'),
('E59', 'nimzo_indian_defense', 'Defensa Nimzoindia', 'Variante normal, Defensa Bernstein'),
('E60', 'kings_indian_defense', 'Defensa India de Rey', NULL),
('E61', 'kings_indian_defense', 'Defensa India de Rey', NULL),
('E62', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Fianchetto diferido'),
('E63', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Variante Panno'),
('E64', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Variante del Pterodáctilo'),
('E65', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Variante yugoslava'),
('E66', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Variante yugoslava, Línea del avance'),
('E67', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Defensa Debrecen'),
('E68', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Variante clásica'),
('E69', 'kings_indian_defense', 'Defensa India de Rey', 'Variante del fianchetto, Línea principal clásica'),
('E70', 'kings_indian_defense', 'Defensa India de Rey', 'Variante normal'),
('E71', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Makogonov'),
('E72', 'kings_indian_defense', 'Defensa India de Rey', 'Variante normal, Fianchetto diferido'),
('E73', 'kings_indian_defense', 'Defensa India de Rey', 'Variante normal, Desarrollo estándar'),
('E74', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Averbakh, Defensa Benoni'),
('E75', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Averbakh, Línea principal'),
('E76', 'kings_indian_defense', 'Defensa India de Rey', 'Ataque de los Cuatro Peones'),
('E77', 'kings_indian_defense', 'Defensa India de Rey', 'Ataque de los Cuatro Peones'),
('E78', 'kings_indian_defense', 'Defensa India de Rey', 'Ataque de los Cuatro Peones, Ataque fluido'),
('E79', 'kings_indian_defense', 'Defensa India de Rey', 'Ataque de los Cuatro Peones, Variante del cambio'),
('E80', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch'),
('E81', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Defensa normal'),
('E82', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Doble fianchetto'),
('E83', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Defensa Yates'),
('E84', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Línea principal Panno'),
('E85', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Variante ortodoxa'),
('E86', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch'),
('E87', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Variante Cerrada'),
('E88', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Variante Cerrada'),
('E89', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Sämisch, Variante Cerrada, Línea principal'),
('E90', 'kings_indian_defense', 'Defensa India de Rey', 'Variante normal, Defensas poco frecuentes'),
('E91', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa'),
('E92', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa'),
('E93', 'kings_indian_defense', 'Defensa India de Rey', 'Variante Petrosian, Defensa normal'),
('E94', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa'),
('E95', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa'),
('E96', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa, Defensa posicional, Línea principal'),
('E97', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa, Defensa Aronin-Taimanov'),
('E98', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa, Sistema clásico'),
('E99', 'kings_indian_defense', 'Defensa India de Rey', 'Variante ortodoxa, Sistema clásico, Línea tradicional')
ON DUPLICATE KEY UPDATE
  family_key = VALUES(family_key),
  opening_name = VALUES(opening_name),
  variation_name = VALUES(variation_name);

INSERT INTO app_migrations (version, description)
VALUES ('1.4.3', 'Canonical Spanish ECO reference catalog')
ON DUPLICATE KEY UPDATE description = VALUES(description);
