<?php
function pgn_moves_text(string $pgn): string {
  $s = preg_replace('/\[[^\]]*\]\s*/', ' ', $pgn);
  while (preg_match('/\([^()]*\)/', $s)) $s = preg_replace('/\([^()]*\)/', ' ', $s);
  $s = preg_replace('/\{[^}]*\}/', ' ', $s);
  $s = preg_replace('/;[^\n\r]*/', ' ', $s);
  $s = preg_replace('/\$\d+/', ' ', $s);
  $s = preg_replace('/\d+\.(\.\.)?/', ' ', $s);
  $s = preg_replace('/\s+/', ' ', trim($s));
  return $s;
}
function initial_board(): array {
  $b=[]; for($r=0;$r<8;$r++) for($f=0;$f<8;$f++) $b[$r][$f]='';
  $back=['r','n','b','q','k','b','n','r'];
  for($f=0;$f<8;$f++){ $b[0][$f]=$back[$f]; $b[1][$f]='p'; $b[6][$f]='P'; $b[7][$f]=strtoupper($back[$f]); }
  return ['b'=>$b,'turn'=>'w','castle'=>'KQkq','ep'=>'-','half'=>0,'full'=>1];
}
function sq_to_rf($sq){ return [8-intval($sq[1]), ord($sq[0])-97]; }
function rf_to_sq($r,$f){ return chr(97+$f).(8-$r); }
function color_piece($p){ if($p==='')return ''; return ctype_upper($p)?'w':'b'; }
function fen_of($st){ $parts=[]; for($r=0;$r<8;$r++){ $row=''; $e=0; for($f=0;$f<8;$f++){ $p=$st['b'][$r][$f]; if($p==='')$e++; else { if($e){$row.=$e;$e=0;} $row.=$p; } } if($e)$row.=$e; $parts[]=$row; } return implode('/',$parts).' '.$st['turn'].' '.($st['castle']?:'-').' '.$st['ep'].' '.$st['half'].' '.$st['full']; }
function in_bounds($r,$f){return $r>=0&&$r<8&&$f>=0&&$f<8;}
function attacked($st,$r,$f,$by){ $b=$st['b']; $pawn=$by==='w'?'P':'p'; $dir=$by==='w'?-1:1; foreach([[-$dir,-1],[-$dir,1]] as $d){$rr=$r+$d[0];$ff=$f+$d[1]; if(in_bounds($rr,$ff)&&$b[$rr][$ff]===$pawn)return true;} $N=$by==='w'?'N':'n'; foreach([[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]] as $d){$rr=$r+$d[0];$ff=$f+$d[1]; if(in_bounds($rr,$ff)&&$b[$rr][$ff]===$N)return true;} foreach([[[1,1],[1,-1],[-1,1],[-1,-1]], $by==='w'?['B','Q']:['b','q']] as $x){} $dirs=[[1,1],[1,-1],[-1,1],[-1,-1]]; foreach($dirs as $d){$rr=$r+$d[0];$ff=$f+$d[1]; while(in_bounds($rr,$ff)){ $p=$b[$rr][$ff]; if($p!==''){ if(in_array($p,$by==='w'?['B','Q']:['b','q']))return true; break;} $rr+=$d[0];$ff+=$d[1]; }} $dirs=[[1,0],[-1,0],[0,1],[0,-1]]; foreach($dirs as $d){$rr=$r+$d[0];$ff=$f+$d[1]; while(in_bounds($rr,$ff)){ $p=$b[$rr][$ff]; if($p!==''){ if(in_array($p,$by==='w'?['R','Q']:['r','q']))return true; break;} $rr+=$d[0];$ff+=$d[1]; }} $K=$by==='w'?'K':'k'; for($dr=-1;$dr<=1;$dr++)for($df=-1;$df<=1;$df++){ if(!$dr&&!$df)continue; $rr=$r+$dr;$ff=$f+$df; if(in_bounds($rr,$ff)&&$b[$rr][$ff]===$K)return true;} return false; }
function king_pos($st,$color){ $K=$color==='w'?'K':'k'; for($r=0;$r<8;$r++)for($f=0;$f<8;$f++) if($st['b'][$r][$f]===$K)return [$r,$f]; return [null,null]; }
function in_check($st,$color){ [$r,$f]=king_pos($st,$color); return $r===null?false:attacked($st,$r,$f,$color==='w'?'b':'w'); }
function apply_move($st,$m){ $b=$st['b']; $p=$b[$m['fr']][$m['ff']]; $cap=$b[$m['tr']][$m['tf']]; $b[$m['fr']][$m['ff']]=''; if(!empty($m['epcap'])) $b[$m['fr']][$m['tf']]=''; if(!empty($m['castle'])){ if($m['tf']==6){$b[$m['tr']][5]=$b[$m['tr']][7];$b[$m['tr']][7]='';} else {$b[$m['tr']][3]=$b[$m['tr']][0];$b[$m['tr']][0]='';} } $b[$m['tr']][$m['tf']]=$m['promo']??$p; $st['b']=$b; $st['ep']='-'; if(strtolower($p)==='p' && abs($m['tr']-$m['fr'])===2) $st['ep']=rf_to_sq(($m['tr']+$m['fr'])/2,$m['ff']); $from=rf_to_sq($m['fr'],$m['ff']); $to=rf_to_sq($m['tr'],$m['tf']); if($p==='K')$st['castle']=str_replace(['K','Q'],'',$st['castle']); if($p==='k')$st['castle']=str_replace(['k','q'],'',$st['castle']); foreach(['a1'=>'Q','h1'=>'K','a8'=>'q','h8'=>'k'] as $sq=>$c){ if($from===$sq||$to===$sq) $st['castle']=str_replace($c,'',$st['castle']); } $st['turn']=$st['turn']==='w'?'b':'w'; if($st['turn']==='w')$st['full']++; return $st; }
function pseudo_moves($st){ $b=$st['b']; $c=$st['turn']; $moves=[]; for($r=0;$r<8;$r++)for($f=0;$f<8;$f++){ $p=$b[$r][$f]; if($p===''||color_piece($p)!==$c)continue; $pl=strtolower($p); $add=function($tr,$tf,$promo=null,$extra=[])use(&$moves,$r,$f,$b,$c){ if(!in_bounds($tr,$tf))return; $t=$b[$tr][$tf]; if($t!==''&&color_piece($t)===$c)return; $moves[]=array_merge(['fr'=>$r,'ff'=>$f,'tr'=>$tr,'tf'=>$tf,'promo'=>$promo],$extra); };
    if($pl==='p'){ $dir=$c==='w'?-1:1; $start=$c==='w'?6:1; $promR=$c==='w'?0:7; if(in_bounds($r+$dir,$f)&&$b[$r+$dir][$f]===''){ if($r+$dir===$promR){foreach(['q','r','b','n'] as $pr)$add($r+$dir,$f,$c==='w'?strtoupper($pr):$pr);} else $add($r+$dir,$f); if($r===$start&&$b[$r+2*$dir][$f]==='')$add($r+2*$dir,$f);} foreach([-1,1] as $df){$tr=$r+$dir;$tf=$f+$df; if(!in_bounds($tr,$tf))continue; $t=$b[$tr][$tf]; $isep=$st['ep']!=='-' && rf_to_sq($tr,$tf)===$st['ep']; if(($t!==''&&color_piece($t)!==$c)||$isep){ if($tr===$promR){foreach(['q','r','b','n'] as $pr)$add($tr,$tf,$c==='w'?strtoupper($pr):$pr,$isep?['epcap'=>1]:[]);} else $add($tr,$tf,null,$isep?['epcap'=>1]:[]); }} }
    elseif($pl==='n'){ foreach([[1,2],[2,1],[-1,2],[-2,1],[1,-2],[2,-1],[-1,-2],[-2,-1]] as $d)$add($r+$d[0],$f+$d[1]); }
    elseif(in_array($pl,['b','r','q'])){ $dirs=[]; if($pl!=='r')$dirs=array_merge($dirs,[[1,1],[1,-1],[-1,1],[-1,-1]]); if($pl!=='b')$dirs=array_merge($dirs,[[1,0],[-1,0],[0,1],[0,-1]]); foreach($dirs as $d){$tr=$r+$d[0];$tf=$f+$d[1]; while(in_bounds($tr,$tf)){ $t=$b[$tr][$tf]; if($t==='')$add($tr,$tf); else { if(color_piece($t)!==$c)$add($tr,$tf); break;} $tr+=$d[0];$tf+=$d[1]; }} }
    elseif($pl==='k'){ for($dr=-1;$dr<=1;$dr++)for($df=-1;$df<=1;$df++){if($dr||$df)$add($r+$dr,$f+$df);} if($c==='w'&&$r==7&&$f==4&&!in_check($st,'w')){ if(strpos($st['castle'],'K')!==false&&$b[7][5]===''&&$b[7][6]===''&&!attacked($st,7,5,'b')&&!attacked($st,7,6,'b'))$add(7,6,null,['castle'=>1]); if(strpos($st['castle'],'Q')!==false&&$b[7][1]===''&&$b[7][2]===''&&$b[7][3]===''&&!attacked($st,7,3,'b')&&!attacked($st,7,2,'b'))$add(7,2,null,['castle'=>1]); } if($c==='b'&&$r==0&&$f==4&&!in_check($st,'b')){ if(strpos($st['castle'],'k')!==false&&$b[0][5]===''&&$b[0][6]===''&&!attacked($st,0,5,'w')&&!attacked($st,0,6,'w'))$add(0,6,null,['castle'=>1]); if(strpos($st['castle'],'q')!==false&&$b[0][1]===''&&$b[0][2]===''&&$b[0][3]===''&&!attacked($st,0,3,'w')&&!attacked($st,0,2,'w'))$add(0,2,null,['castle'=>1]); } }
  } $legal=[]; foreach($moves as $m){$ns=apply_move($st,$m); if(!in_check($ns,$c))$legal[]=$m;} return $legal; }
function clean_san($san){ $san=trim($san); $san=preg_replace('/[!?+#]+/','',$san); return $san; }
function san_to_move($st,$san){ $san=clean_san($san); if($san==='O-O'||$san==='0-0')$san='O-O'; if($san==='O-O-O'||$san==='0-0-0')$san='O-O-O'; $moves=pseudo_moves($st); if($san==='O-O'||$san==='O-O-O'){ foreach($moves as $m) if(!empty($m['castle']) && (($san==='O-O'&&$m['tf']==6)||($san==='O-O-O'&&$m['tf']==2))) return $m; }
  $promo=null; if(preg_match('/=([QRBNqrbn])/', $san,$pm)){ $promo=$st['turn']==='w'?strtoupper($pm[1]):strtolower($pm[1]); $san=preg_replace('/=([QRBNqrbn])/','',$san); }
  $target=substr($san,-2); if(!preg_match('/^[a-h][1-8]$/',$target)) return null; [$tr,$tf]=sq_to_rf($target); $lead=substr($san,0,-2); $piece='P'; if($lead!==''&&strpos('KQRBN',$lead[0])!==false){$piece=$lead[0];$lead=substr($lead,1);} $lead=str_replace('x','',$lead); $fromFile=null;$fromRank=null; foreach(str_split($lead) as $ch){ if($ch>='a'&&$ch<='h')$fromFile=ord($ch)-97; if($ch>='1'&&$ch<='8')$fromRank=8-intval($ch); }
  foreach($moves as $m){ $p=$st['b'][$m['fr']][$m['ff']]; if(strtoupper($p)!==$piece)continue; if($m['tr']!==$tr||$m['tf']!==$tf)continue; if($promo!==null && ($m['promo']??null)!==$promo)continue; if($fromFile!==null && $m['ff']!==$fromFile)continue; if($fromRank!==null && $m['fr']!==$fromRank)continue; return $m; } return null; }
function pgn_to_uci_positions(string $pgn): array { $tokens=explode(' ',pgn_moves_text($pgn)); $st=initial_board(); $out=[]; foreach($tokens as $tok){ if($tok===''||in_array($tok,['1-0','0-1','1/2-1/2','*']))continue; $m=san_to_move($st,$tok); if(!$m) throw new Exception('No puedo interpretar la jugada PGN: '.$tok); $uci=rf_to_sq($m['fr'],$m['ff']).rf_to_sq($m['tr'],$m['tf']); if(!empty($m['promo']))$uci.=strtolower($m['promo']); $out[]=['san'=>$tok,'uci'=>$uci,'fen_before'=>fen_of($st)]; $st=apply_move($st,$m); $out[count($out)-1]['fen_after']=fen_of($st); } return $out; }
