-- Chess Coach PWA v0.9.0 - instalación completa
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(80) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  piece_set VARCHAR(80) NOT NULL DEFAULT 'Set 1',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS games (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  game_uid CHAR(64) NOT NULL,
  white_player VARCHAR(120) DEFAULT NULL,
  black_player VARCHAR(120) DEFAULT NULL,
  result_raw VARCHAR(20) DEFAULT NULL,
  user_result ENUM('win','loss','draw','unknown') NOT NULL DEFAULT 'unknown',
  played_at DATE DEFAULT NULL,
  event_name VARCHAR(255) DEFAULT NULL,
  site VARCHAR(255) DEFAULT NULL,
  eco_code VARCHAR(10) DEFAULT NULL,
  opening_name VARCHAR(255) DEFAULT NULL,
  eco_url VARCHAR(500) DEFAULT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'manual',
  pgn MEDIUMTEXT NOT NULL,
  imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_games_user_uid (user_id, game_uid),
  KEY idx_games_user_date (user_id, played_at),
  KEY idx_games_opening (eco_code),
  KEY idx_games_source (source),
  CONSTRAINT fk_games_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS game_analysis (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  game_id BIGINT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  engine_name VARCHAR(80) NOT NULL DEFAULT 'Stockfish',
  engine_depth INT UNSIGNED DEFAULT NULL,
  status ENUM('queued','running','done','error','cancelled') NOT NULL DEFAULT 'queued',
  blunders INT UNSIGNED NOT NULL DEFAULT 0,
  mistakes INT UNSIGNED NOT NULL DEFAULT 0,
  inaccuracies INT UNSIGNED NOT NULL DEFAULT 0,
  current_ply INT UNSIGNED NOT NULL DEFAULT 0,
  total_ply INT UNSIGNED NOT NULL DEFAULT 0,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  cancel_requested TINYINT(1) NOT NULL DEFAULT 0,
  error_message TEXT DEFAULT NULL,
  started_at TIMESTAMP NULL DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_analysis_game (game_id),
  KEY idx_analysis_user (user_id),
  KEY idx_analysis_queue (user_id, status, created_at),
  CONSTRAINT fk_analysis_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_analysis_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS game_move_analysis (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  analysis_id BIGINT UNSIGNED NOT NULL,
  ply INT UNSIGNED NOT NULL,
  san VARCHAR(30) NOT NULL,
  uci VARCHAR(10) NOT NULL,
  fen_before VARCHAR(120) NOT NULL,
  fen_after VARCHAR(120) NOT NULL,
  bestmove VARCHAR(10) DEFAULT NULL,
  score_before INT DEFAULT NULL,
  score_before_type ENUM('cp','mate') NOT NULL DEFAULT 'cp',
  score_after INT DEFAULT NULL,
  score_after_type ENUM('cp','mate') NOT NULL DEFAULT 'cp',
  centipawn_loss INT UNSIGNED NOT NULL DEFAULT 0,
  classification ENUM('ok','inaccuracy','mistake','blunder') NOT NULL DEFAULT 'ok',
  PRIMARY KEY (id),
  UNIQUE KEY uq_move_analysis_ply (analysis_id, ply),
  KEY idx_move_classification (classification),
  CONSTRAINT fk_move_analysis FOREIGN KEY (analysis_id) REFERENCES game_analysis(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS game_opening_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  game_id BIGINT UNSIGNED NOT NULL,
  analysis_id BIGINT UNSIGNED DEFAULT NULL,
  user_color ENUM('white','black','unknown') NOT NULL DEFAULT 'unknown',
  opening_key VARCHAR(320) NOT NULL,
  display_name VARCHAR(320) NOT NULL,
  eco_code VARCHAR(10) DEFAULT NULL,
  opening_name VARCHAR(255) DEFAULT NULL,
  eco_url VARCHAR(500) DEFAULT NULL,
  opening_source ENUM('pgn','eco','signature','unknown') NOT NULL DEFAULT 'unknown',
  opening_signature VARCHAR(255) DEFAULT NULL,
  first_moves_san TEXT DEFAULT NULL,
  first_moves_uci TEXT DEFAULT NULL,
  plies_count TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_opening_profile_game (user_id, game_id),
  KEY idx_opening_profiles_user_key (user_id, opening_key),
  KEY idx_opening_profiles_user_color (user_id, user_color),
  KEY idx_opening_profiles_eco (eco_code),
  KEY idx_opening_profiles_analysis (analysis_id),
  CONSTRAINT fk_opening_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_opening_profiles_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_opening_profiles_analysis FOREIGN KEY (analysis_id) REFERENCES game_analysis(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS analysis_worker_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  trigger_source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  queue_before INT UNSIGNED NOT NULL DEFAULT 0,
  queue_after INT UNSIGNED NOT NULL DEFAULT 0,
  processed_count INT UNSIGNED NOT NULL DEFAULT 0,
  success_count INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  last_analysis_id BIGINT UNSIGNED DEFAULT NULL,
  last_status VARCHAR(20) DEFAULT NULL,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_worker_runs_user (user_id, created_at),
  KEY idx_worker_runs_analysis (last_analysis_id),
  CONSTRAINT fk_worker_runs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_worker_runs_analysis FOREIGN KEY (last_analysis_id) REFERENCES game_analysis(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chesscom_imports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  chesscom_username VARCHAR(80) NOT NULL,
  requested_limit INT UNSIGNED NOT NULL,
  imported_count INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  status ENUM('done','error') NOT NULL DEFAULT 'done',
  error_message TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chesscom_user (user_id, created_at),
  CONSTRAINT fk_chesscom_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smart_tag_definitions (
  code VARCHAR(60) NOT NULL,
  label VARCHAR(80) NOT NULL,
  scope ENUM('game','move','both') NOT NULL DEFAULT 'both',
  category VARCHAR(40) NOT NULL DEFAULT 'general',
  severity ENUM('info','low','medium','high','critical') NOT NULL DEFAULT 'info',
  description VARCHAR(255) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (code),
  KEY idx_smart_tag_scope (scope),
  KEY idx_smart_tag_category (category),
  KEY idx_smart_tag_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS game_tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  game_id BIGINT UNSIGNED NOT NULL,
  analysis_id BIGINT UNSIGNED NOT NULL,
  tag_code VARCHAR(60) NOT NULL,
  confidence DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  evidence_count INT UNSIGNED NOT NULL DEFAULT 0,
  primary_ply INT UNSIGNED DEFAULT NULL,
  details_json TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_game_tag_analysis_code (analysis_id, tag_code),
  KEY idx_game_tags_user_tag (user_id, tag_code),
  KEY idx_game_tags_game (game_id),
  KEY idx_game_tags_analysis (analysis_id),
  KEY idx_game_tags_tag (tag_code),
  CONSTRAINT fk_game_tags_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_game_tags_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_game_tags_analysis FOREIGN KEY (analysis_id) REFERENCES game_analysis(id) ON DELETE CASCADE,
  CONSTRAINT fk_game_tags_definition FOREIGN KEY (tag_code) REFERENCES smart_tag_definitions(code) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS move_tags (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  game_id BIGINT UNSIGNED NOT NULL,
  analysis_id BIGINT UNSIGNED NOT NULL,
  move_analysis_id BIGINT UNSIGNED NOT NULL,
  ply INT UNSIGNED NOT NULL,
  tag_code VARCHAR(60) NOT NULL,
  confidence DECIMAL(5,2) NOT NULL DEFAULT 1.00,
  severity ENUM('info','low','medium','high','critical') NOT NULL DEFAULT 'info',
  details_json TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_move_tag_move_code (move_analysis_id, tag_code),
  KEY idx_move_tags_user_tag (user_id, tag_code),
  KEY idx_move_tags_game (game_id),
  KEY idx_move_tags_analysis (analysis_id),
  KEY idx_move_tags_move (move_analysis_id),
  KEY idx_move_tags_tag (tag_code),
  CONSTRAINT fk_move_tags_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_move_tags_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_move_tags_analysis FOREIGN KEY (analysis_id) REFERENCES game_analysis(id) ON DELETE CASCADE,
  CONSTRAINT fk_move_tags_move FOREIGN KEY (move_analysis_id) REFERENCES game_move_analysis(id) ON DELETE CASCADE,
  CONSTRAINT fk_move_tags_definition FOREIGN KEY (tag_code) REFERENCES smart_tag_definitions(code) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS smart_tag_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  trigger_source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  status ENUM('running','done','error') NOT NULL DEFAULT 'running',
  processed_games INT UNSIGNED NOT NULL DEFAULT 0,
  tagged_games INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(255) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_smart_tag_runs_user (user_id, started_at),
  KEY idx_smart_tag_runs_status (status),
  CONSTRAINT fk_smart_tag_runs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS opening_profile_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  trigger_source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  status ENUM('running','done','error') NOT NULL DEFAULT 'running',
  processed_games INT UNSIGNED NOT NULL DEFAULT 0,
  updated_profiles INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(255) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_opening_profile_runs_user_started (user_id, started_at),
  KEY idx_opening_profile_runs_status (status),
  CONSTRAINT fk_opening_profile_runs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS player_dna_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  trigger_source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  period_size TINYINT UNSIGNED NOT NULL DEFAULT 10,
  minimum_games TINYINT UNSIGNED NOT NULL DEFAULT 6,
  analyzed_games INT UNSIGNED NOT NULL DEFAULT 0,
  recent_games INT UNSIGNED NOT NULL DEFAULT 0,
  previous_games INT UNSIGNED NOT NULL DEFAULT 0,
  baseline_games INT UNSIGNED NOT NULL DEFAULT 0,
  current_month_games INT UNSIGNED NOT NULL DEFAULT 0,
  previous_month_games INT UNSIGNED NOT NULL DEFAULT 0,
  latest_analysis_id BIGINT UNSIGNED DEFAULT NULL,
  latest_game_id BIGINT UNSIGNED DEFAULT NULL,
  latest_game_date DATE DEFAULT NULL,
  confidence ENUM('low','medium','high') NOT NULL DEFAULT 'low',
  profile_label VARCHAR(120) DEFAULT NULL,
  summary_text TEXT DEFAULT NULL,
  dimensions_json MEDIUMTEXT NOT NULL,
  style_json MEDIUMTEXT NOT NULL,
  strengths_json MEDIUMTEXT NOT NULL,
  weaknesses_json MEDIUMTEXT NOT NULL,
  comparisons_json MEDIUMTEXT NOT NULL,
  recommendations_json MEDIUMTEXT DEFAULT NULL,
  generated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_player_dna_user_generated (user_id, generated_at),
  KEY idx_player_dna_user_confidence (user_id, confidence),
  KEY idx_player_dna_latest_analysis (latest_analysis_id),
  KEY idx_player_dna_latest_game (latest_game_id),
  CONSTRAINT fk_player_dna_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_player_dna_snapshots_analysis FOREIGN KEY (latest_analysis_id) REFERENCES game_analysis(id) ON DELETE SET NULL,
  CONSTRAINT fk_player_dna_snapshots_game FOREIGN KEY (latest_game_id) REFERENCES games(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS player_dna_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  snapshot_id BIGINT UNSIGNED DEFAULT NULL,
  trigger_source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  status ENUM('running','done','error') NOT NULL DEFAULT 'running',
  processed_games INT UNSIGNED NOT NULL DEFAULT 0,
  generated_snapshots INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(255) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_player_dna_runs_user_started (user_id, started_at),
  KEY idx_player_dna_runs_status (status),
  KEY idx_player_dna_runs_snapshot (snapshot_id),
  CONSTRAINT fk_player_dna_runs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_player_dna_runs_snapshot FOREIGN KEY (snapshot_id) REFERENCES player_dna_snapshots(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_exercises (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  game_id BIGINT UNSIGNED NOT NULL,
  analysis_id BIGINT UNSIGNED NOT NULL,
  move_analysis_id BIGINT UNSIGNED NOT NULL,
  ply INT UNSIGNED NOT NULL,
  source_side ENUM('user','opponent') NOT NULL DEFAULT 'user',
  exercise_type ENUM('find_best_move','avoid_blunder','find_mate','spot_threat','find_tactic','defend_position','convert_advantage','other') NOT NULL DEFAULT 'find_best_move',
  fen VARCHAR(120) NOT NULL,
  solution_uci VARCHAR(10) NOT NULL,
  solution_san VARCHAR(30) DEFAULT NULL,
  played_uci VARCHAR(10) DEFAULT NULL,
  played_san VARCHAR(30) DEFAULT NULL,
  centipawn_loss INT UNSIGNED NOT NULL DEFAULT 0,
  classification ENUM('ok','inaccuracy','mistake','blunder') NOT NULL DEFAULT 'ok',
  difficulty ENUM('easy','medium','hard','critical') NOT NULL DEFAULT 'medium',
  priority_score INT NOT NULL DEFAULT 0,
  source_focus_code VARCHAR(40) DEFAULT NULL,
  prompt VARCHAR(255) NOT NULL,
  feedback_success VARCHAR(255) DEFAULT NULL,
  feedback_failure VARCHAR(255) DEFAULT NULL,
  status ENUM('active','archived') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP NULL DEFAULT NULL,
  last_attempt_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_training_exercise_move_type (user_id, move_analysis_id, exercise_type),
  KEY idx_training_exercises_user_status (user_id, status, resolved_at, priority_score),
  KEY idx_training_exercises_user_type (user_id, exercise_type, status),
  KEY idx_training_exercises_source (user_id, source_side, priority_score),
  KEY idx_training_exercises_game (game_id),
  KEY idx_training_exercises_analysis (analysis_id),
  KEY idx_training_exercises_move (move_analysis_id),
  CONSTRAINT fk_training_exercises_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_exercises_game FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_exercises_analysis FOREIGN KEY (analysis_id) REFERENCES game_analysis(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_exercises_move FOREIGN KEY (move_analysis_id) REFERENCES game_move_analysis(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_exercise_tags (
  exercise_id BIGINT UNSIGNED NOT NULL,
  tag_code VARCHAR(60) NOT NULL,
  source ENUM('move','game','focus') NOT NULL DEFAULT 'move',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (exercise_id, tag_code, source),
  KEY idx_training_exercise_tags_tag (tag_code),
  CONSTRAINT fk_training_exercise_tags_exercise FOREIGN KEY (exercise_id) REFERENCES training_exercises(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_exercise_tags_definition FOREIGN KEY (tag_code) REFERENCES smart_tag_definitions(code) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NOT NULL,
  focus_code VARCHAR(40) DEFAULT NULL,
  selected_type ENUM('recommended','find_best_move','avoid_blunder','find_mate','spot_threat','find_tactic','defend_position','convert_advantage','other') NOT NULL DEFAULT 'recommended',
  source ENUM('manual','dashboard','recommended') NOT NULL DEFAULT 'manual',
  status ENUM('active','completed','abandoned') NOT NULL DEFAULT 'active',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  exercise_count INT UNSIGNED NOT NULL DEFAULT 0,
  solved_count INT UNSIGNED NOT NULL DEFAULT 0,
  failed_count INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_count INT UNSIGNED NOT NULL DEFAULT 0,
  total_attempts INT UNSIGNED NOT NULL DEFAULT 0,
  avg_time_ms INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_training_sessions_user_started (user_id, started_at),
  KEY idx_training_sessions_user_status (user_id, status),
  CONSTRAINT fk_training_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_attempts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_id BIGINT UNSIGNED DEFAULT NULL,
  exercise_id BIGINT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  attempts_count INT UNSIGNED NOT NULL DEFAULT 0,
  first_move_uci VARCHAR(10) DEFAULT NULL,
  final_move_uci VARCHAR(10) DEFAULT NULL,
  attempted_moves_json TEXT DEFAULT NULL,
  is_solved TINYINT(1) NOT NULL DEFAULT 0,
  result ENUM('solved','failed','skipped') NOT NULL DEFAULT 'failed',
  used_hint TINYINT(1) NOT NULL DEFAULT 0,
  difficulty_after_attempt ENUM('easy','medium','hard','critical') DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_training_attempts_user_created (user_id, created_at),
  KEY idx_training_attempts_exercise (exercise_id, created_at),
  KEY idx_training_attempts_session (session_id),
  CONSTRAINT fk_training_attempts_session FOREIGN KEY (session_id) REFERENCES training_sessions(id) ON DELETE SET NULL,
  CONSTRAINT fk_training_attempts_exercise FOREIGN KEY (exercise_id) REFERENCES training_exercises(id) ON DELETE CASCADE,
  CONSTRAINT fk_training_attempts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS training_generation_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED DEFAULT NULL,
  trigger_source VARCHAR(40) NOT NULL DEFAULT 'unknown',
  status ENUM('running','done','error') NOT NULL DEFAULT 'running',
  processed_moves INT UNSIGNED NOT NULL DEFAULT 0,
  created_exercises INT UNSIGNED NOT NULL DEFAULT 0,
  skipped_existing INT UNSIGNED NOT NULL DEFAULT 0,
  error_count INT UNSIGNED NOT NULL DEFAULT 0,
  duration_ms INT UNSIGNED NOT NULL DEFAULT 0,
  message VARCHAR(255) DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY idx_training_generation_user_started (user_id, started_at),
  KEY idx_training_generation_status (status),
  CONSTRAINT fk_training_generation_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS motivational_quotes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  quote_text VARCHAR(255) NOT NULL,
  author VARCHAR(120) NOT NULL,
  source_name VARCHAR(120) DEFAULT NULL,
  source_url VARCHAR(255) DEFAULT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  display_order INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_motivational_quote_text (quote_text),
  KEY idx_motivational_quotes_active (is_active),
  KEY idx_motivational_quotes_order (display_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS app_migrations (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  version VARCHAR(30) NOT NULL,
  description VARCHAR(255) NOT NULL,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_app_migrations_version (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (username, password_hash)
VALUES ('sperales', '$2y$12$1zypokfJvKDhAYgsiVuK1Outhq2uKUMHmr.WcoYdNpU9WPyXRmoxC')
ON DUPLICATE KEY UPDATE username = username;

INSERT INTO smart_tag_definitions (code, label, scope, category, severity, description, is_active) VALUES
('blunder_own', 'Omisión grave', 'both', 'error', 'critical', 'Jugada propia con una pérdida muy alta de evaluación.', 1),
('mistake_own', 'Error importante', 'both', 'error', 'high', 'Jugada propia que concede una oportunidad clara al rival.', 1),
('inaccuracy_own', 'Imprecisión', 'both', 'error', 'low', 'Jugada propia que deja escapar parte de la ventaja o iniciativa.', 1),
('opening_issue', 'Problema de apertura', 'game', 'phase', 'medium', 'La partida contiene errores relevantes en la fase inicial.', 1),
('endgame_mistake', 'Error en final', 'game', 'phase', 'high', 'La partida contiene un error relevante en el tramo final.', 1),
('missed_mate', 'Mate omitido', 'move', 'tactical', 'critical', 'La posición ofrecía una secuencia de mate favorable que no se aprovechó.', 1),
('allowed_mate', 'Mate permitido', 'move', 'tactical', 'critical', 'La jugada permitió una secuencia de mate favorable al rival.', 1),
('lost_winning_position', 'Ventaja desperdiciada', 'game', 'error', 'high', 'La partida pasó de una ventaja clara a una posición igualada o peor.', 1),
('comeback', 'Remontada', 'game', 'positive', 'medium', 'La partida terminó bien después de haber estado claramente peor.', 1),
('converted_advantage', 'Ventaja convertida', 'game', 'positive', 'medium', 'La partida convirtió una ventaja clara en un buen resultado.', 1),
('precise_game', 'Partida precisa', 'game', 'positive', 'low', 'La partida tuvo pocas pérdidas relevantes de evaluación.', 1),
('strong_finish', 'Buen tramo final', 'game', 'positive', 'low', 'La partida mantuvo o mejoró la evaluación en el tramo final.', 1)
ON DUPLICATE KEY UPDATE
  label = VALUES(label),
  scope = VALUES(scope),
  category = VALUES(category),
  severity = VALUES(severity),
  description = VALUES(description),
  is_active = VALUES(is_active);

INSERT INTO motivational_quotes (quote_text, author, source_name, source_url, is_active, display_order) VALUES
('Para mejorar, estudia el final antes que cualquier otra cosa.', 'José Raúl Capablanca', 'Wikiquote', 'https://en.wikiquote.org/wiki/Jos%C3%A9_Ra%C3%BAl_Capablanca', 1, 10),
('El buen ajedrez nace de pensar por ti mismo.', 'Emanuel Lasker', 'Wikiquote', 'https://en.wikiquote.org/wiki/Emanuel_Lasker', 1, 20),
('Recuerda métodos, no solo variantes.', 'Emanuel Lasker', 'Wikiquote', 'https://en.wikiquote.org/wiki/Emanuel_Lasker', 1, 30),
('El ajedrez, como la música, tiene poder para hacernos felices.', 'Siegbert Tarrasch', 'Wikiquote', 'https://en.wikiquote.org/wiki/Siegbert_Tarrasch', 1, 40),
('Muchos llegaron a maestros; nadie ha dominado por completo el ajedrez.', 'Siegbert Tarrasch', 'Wikiquote', 'https://en.wikiquote.org/wiki/Siegbert_Tarrasch', 1, 50),
('Antes del final, los dioses pusieron el medio juego.', 'Siegbert Tarrasch', 'Wikiquote', 'https://en.wikiquote.org/wiki/Siegbert_Tarrasch', 1, 60),
('En torneo no basta con saber ajedrez: también hay que jugar bien.', 'Siegbert Tarrasch', 'Wikiquote', 'https://en.wikiquote.org/wiki/Siegbert_Tarrasch', 1, 70),
('La desconfianza es una cualidad necesaria del ajedrecista.', 'Siegbert Tarrasch', 'Wikiquote', 'https://en.wikiquote.org/wiki/Siegbert_Tarrasch', 1, 80),
('En ajedrez no hay nada accidental.', 'Tigran Petrosian', 'Wikiquote', 'https://en.wikiquote.org/wiki/Chess', 1, 90),
('El ajedrez es el juego del filósofo.', 'Paul Morphy', 'Wikiquote', 'https://en.wikiquote.org/wiki/Chess', 1, 100),
('El ajedrez enseña previsión, prudencia y cautela.', 'Benjamin Franklin', 'Wikiquote', 'https://en.wikiquote.org/wiki/Chess', 1, 110),
('El objetivo de la apertura es llegar a un medio juego jugable.', 'Savielly Tartakower', 'Wikiquote', 'https://en.wikiquote.org/wiki/Savielly_Tartakower', 1, 120),
('La partida se gana con buenas jugadas, una detrás de otra.', 'Savielly Tartakower', 'Wikiquote', 'https://en.wikiquote.org/wiki/Savielly_Tartakower', 1, 130),
('Quien arriesga puede perder; quien no arriesga siempre pierde.', 'Savielly Tartakower', 'Wikiquote', 'https://en.wikiquote.org/wiki/Savielly_Tartakower', 1, 140),
('Una mala idea es mejor que no tener ningún plan.', 'Frank Marshall', 'Wikiquote', 'https://en.wikiquote.org/wiki/Chess', 1, 150)
ON DUPLICATE KEY UPDATE
  author = VALUES(author),
  source_name = VALUES(source_name),
  source_url = VALUES(source_url),
  is_active = VALUES(is_active),
  display_order = VALUES(display_order);

INSERT INTO app_migrations (version, description) VALUES
('0.5.1', 'Initial MariaDB schema, login, profile password change and game storage'),
('0.5.2', 'Import PGN collapsed by default'),
('0.5.3', 'Separated app and database configuration'),
('0.5.4', 'Refactored project structure and removed legacy private folder'),
('0.6.0', 'Server-side Stockfish analysis and Chess.com import'),
('0.6.1', 'Background-like analysis UX and result badges'),
('0.6.3', 'Games pagination'),
('0.6.5', 'Home redesign and unified import page'),
('0.6.7', 'Header-only navigation and approved logo'),
('0.7.0', 'Automatic analysis queue and worker'),
('0.7.1', 'Cron token and worker execution history'),
('0.7.2', 'Home toggle, 6-hour cron estimate and regenerated PWA icons'),
('0.8.0', 'Chess Review with evaluation graph and move-by-move review'),
('0.8.1', 'Review board piece colors and normalized evaluation graph'),
('0.8.2', 'Review fixes for mate scores, ACPL and final evaluation'),
('0.8.3', 'Chess.com style SVG piece set integrated into review board'),
('0.8.4', 'Replace chess piece assets with PNG set'),
('0.8.5', 'Return to Unicode pieces and fix migration SQL'),
('0.9.0', 'Smart Tags schema and initial tag catalog'),
('0.9.2', 'Home motivational quotes catalog'),
('1.1.0', 'Training Center foundation schema'),
('1.1.5', 'User-selectable chess piece sets'),
('1.2.0', 'Openings Lab data foundation'),
('1.3.0', 'Player DNA data foundation')
ON DUPLICATE KEY UPDATE version = version;
